# Generated by Django 4.0.2 on 2022-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='res_image',
            field=models.ImageField(blank=True, upload_to='itemImages'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='res_image',
            field=models.ImageField(blank=True, upload_to='resImages'),
        ),
    ]
