# Generated by Django 4.0.2 on 2022-05-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_res_image_restaurant_res_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField()),
                ('is_added_to_cart', models.BooleanField(default=False)),
                ('is_checkout', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('cart_added_date', models.DateTimeField(auto_now_add=True)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('order_complete_date', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_order', to='food.item')),
                ('restaurant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_restaurant', to='food.restaurant')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
