# Generated by Django 4.0.2 on 2022-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_added_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_complete_date',
            field=models.DateTimeField(),
        ),
    ]
